### ISSUE TITLE
unable to define outbound email address different to mailbox user

### ISSUE THREAD

**Issue by nysander** [X2Engine/X2CRM#100]
I got such setup:

mailbox user js@example.com
email alias john.smith@example.com

when I define above in smtp section I cannot define such mailbox as imap mailbox (user unknown to email server as john.smith@example.com is only alias and app uses it as IMAP login)

when i define email as js@example.com IMAP works fine but sending mails from mail client does not allow me to choose which mailbox to use and sends them showing js@example.com as sender. I wanted it to use as sender my alias.

When I enter contact and then create email I can choose which mailbox to use and then it uses my alias as sender. This should work the same in both places.

**Comment by nysander** [comment]
another issue with sending emails from mailbox not connected to imap is that this emails are only stored inside CRM not in my Sent mailbox.

**Comment by nysander** [comment]
closing unresolved due to no contact with maintainer

**Comment by pczupil** [comment]
Thank you for contacting us Nysander. However this is a feature request, please use our forums for feature requests: http://community.x2crm.com/forum/8-feature-requests/
