### ISSUE TITLE
Stored XSS in module name 

### ISSUE THREAD

**Issue by Fadavvi** [X2Engine/X2CRM#162]
Hi agian

Description :
XSS in module name will prompt in all other pages of X2CRM CE V6.9

Sample Pic:
![ezgif-4-97e4273b25ba](https://user-images.githubusercontent.com/21213484/48061148-39de0200-e1d3-11e8-88c1-a7a952e02971.gif)

Payload to use : "><img src=x onerror=prompt('@darknetguy');>

Tested on Windows 10 Firefox | Google Chrome // Cent-OS 7 Firefox | Chromium

BR,

Milad Fadavvi

**Comment by pczupil** [comment]
Thank you for the info Milad. We will have this fixed in our next release. I will keep this issue open until we have confirmed that the XSS has been removed.
