### ISSUE TITLE
Quotes/Invoice Modules

### ISSUE THREAD

**Issue by dabisaworldwide** [X2Engine/X2CRM#79]
Hi!
How would I disable a module like invoices/Quotes if I do not need it. I love everything about X2CRM but my accounting system already accomplishes any Of the capabilities offered by these two modules. 

Any insight or guidance, would be greatly appreciated.

**Comment by raymondcolebaugh** [comment]
The modules in X2CRM can be hidden by navigating to the admin page and following the link to "Manage Menu Items" under User Interface Settings.

**Comment by dabisaworldwide** [comment]
Hi!
I thank you for the reply! I just wanted to point out that even when the quotes/invoice module is hidden; it is not hidden as an option in the sidebars in the other modules such as opportunities - Which mean it is still accessible to users in the system. Any work around for that, please?
